[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "PesticideRework"
description = "Enhances Pesticide flamethrower with turbocharged range boost and damage scaling with enemy missing health."
websiteUrl = "https://github.com/Little-Sparroh/PesticideRework"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/PesticideRework.dll"
target = "BepInEx/plugins/PesticideRework.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]
